import OphGap.OphWitness
import OphGap.OphOrigData

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

theorem origNodes_length : origNodes.length = 8662 := by decide +kernel
theorem origEdges_length : origEdges.length = 11816 := by decide +kernel
theorem part_len : decide (origNodes.length = n) = true := by decide +kernel
theorem part_lenEq : decide (origEdges.length = edges.length) = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem part_sorted : sortedOk origNodes = true := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodes_1 : nodesOk n newT oldT (origNodes.take 3000) = true := by decide +kernel

end GapScout.Oph
