import OphGap.Slices.N1

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem nodes_2 : nodesOk n newT oldT ((origNodes.drop 3000).take 3000) = true := by decide +kernel

end GapScout.Oph
