import OphGap.Slices.T3

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem perm_1 : permOk (newF newT) permT invPermT edgesT edges.length 0 (origEdges.take 3000) = true := by decide +kernel

end GapScout.Oph
