import OphGap.Slices.P1

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem perm_2 : permOk (newF newT) permT invPermT edgesT edges.length 3000 ((origEdges.drop 3000).take 3000) = true := by decide +kernel

end GapScout.Oph
