import OphGap.Slices.P2

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem perm_3 : permOk (newF newT) permT invPermT edgesT edges.length 6000 (((origEdges.drop 3000).drop 3000).take 3000) = true := by decide +kernel

end GapScout.Oph
