import OphGap.Slices.E3

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem edgesT_1 : edgesTOk edgesT 0 (edges.take 4000) = true := by decide +kernel

end GapScout.Oph
