import OphGap.Slices.T1

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph

set_option maxRecDepth 100000 in
theorem edgesT_2 : edgesTOk edgesT 4000 ((edges.drop 4000).take 4000) = true := by decide +kernel

end GapScout.Oph
