"""Emit OphGap/OphOrigData.lean: OPH's seam graph with its ORIGINAL carrier ids, plus
two lookup trees (carrier id -> BFS label, BFS label -> carrier id) used as HINTS by the
Lean kernel checks in OphOrigWitness.lean. Nothing emitted here is trusted: every table
is re-checked by the kernel (nodesOk / endpointsOk / multiset equality).

Inputs (pure data):
  graph.json   -- OPH's seam complex as produced by OPH's own seam_complex(): sorted node
                  list, edge list in OPH's order/orientation, signs. freeze sha256 a0be6fc6...
  cert.json    -- the BFS relabel map used by certify.py for OphData.lean (new label per id)
"""
import json, sys, hashlib
src = sys.argv[1] if len(sys.argv) > 1 else "/home/monkey/scratch/gapwitness"
g = json.load(open(f"{src}/graph.json"))
cert = json.load(open(f"{src}/cert.json"))
nodes, edges = g["nodes"], g["edges"]
new = {int(k): v for k, v in cert["relabel"].items()}
n = len(nodes)
assert sorted(new.values()) == list(range(n)) and set(new) == set(nodes)
old = {v: k for k, v in new.items()}

def build(d):
    """Binary trie keyed by bits from the LSB; mirrors NTree.get in Transport.lean."""
    if not d: return None
    v = d.get(0)
    l = build({k // 2: x for k, x in d.items() if k % 2 == 1})
    r = build({k // 2: x for k, x in d.items() if k > 0 and k % 2 == 0})
    return (v, l, r)

def get(t, k):
    while True:
        if t is None: return None
        v, l, r = t
        if k == 0: return v
        t, k = (l, k // 2) if k % 2 == 1 else (r, k // 2)

defs = []
def emit(t, name, ty, depth=0):
    if t is None: return "leaf"
    v, l, r = t
    vs = "none" if v is None else f"(some {v})"
    s = f"(node {vs} {emit(l, name, ty, depth+1)} {emit(r, name, ty, depth+1)})"
    if depth == 4:
        defs.append(f"def {name}_{len(defs)} : {ty} := {s}\n")
        return f"{name}_{len(defs)-1}"
    return s

def fmt_edge(e):
    a, b, s = e
    return f"({a},{b},{'true' if s else 'false'})"

newT, oldT = build(new), build(old)
for k, v in new.items(): assert get(newT, k) == v and get(oldT, v) == k
for a, b, s in edges: assert a in new and b in new and a != b

# edge permutation: original index i -> index j in the relabelled list (OphData.lean) with the
# same canonical (min,max,neg) edge. Relabelled list reproduced from edges_relabeled.json.
rel = json.load(open(f"{src}/edges_relabeled.json"))
def canon(a, b, neg): return (a, b, neg) if a <= b else (b, a, neg)
where = {}
for j, (a, b, neg) in enumerate(rel):
    key = canon(a, b, neg); assert key not in where, "duplicate canonical edge"; where[key] = j
perm = {}
for i, (a, b, s) in enumerate(edges):
    perm[i] = where[canon(new[a], new[b], s == -1)]
assert sorted(perm.values()) == list(range(len(rel))) and len(rel) == len(edges)
invperm = {j: i for i, j in perm.items()}
edgesT_d = {j: canon(a, b, neg) for j, (a, b, neg) in enumerate(rel)}
permT, invPermT, edgesT = build(perm), build(invperm), build(edgesT_d)

L = ["import OphGap.Transport\n",
     "/-! AUTO-GENERATED by tools/gen_orig_data.py. OPH's frozen visible seam complex with its",
     "   ORIGINAL carrier ids (freeze sha256 a0be6fc6...), in OPH's own node order and edge",
     f"   order/orientation: n={n} nodes, m={len(edges)} edges, Edge = (a, b, negative?).",
     "   `newT`/`oldT`/`permT`/`invPermT`/`edgesT` are lookup tries (vertex relabelling, edge",
     "   permutation, canonical-edge table) that are HINTS only; the kernel",
     "   re-checks them in OphOrigWitness.lean. -/\n",
     "namespace GapScout.Oph\nopen Trie\n"]
CH = 400
nchunks = [nodes[i:i+CH] for i in range(0, n, CH)]
for k, ch in enumerate(nchunks):
    L.append(f"def nodeChunk{k} : List Nat := [{','.join(map(str, ch))}]\n")
L.append("/-- OPH's sorted carrier-id list (`seam_complex(...)[\"nodes\"]`). -/\ndef origNodes : List Nat :=\n  "
         + " ++ ".join(f"nodeChunk{k}" for k in range(len(nchunks))) + "\n")
echunks = [edges[i:i+CH] for i in range(0, len(edges), CH)]
for k, ch in enumerate(echunks):
    body = ",".join(f"({a},{b},{'true' if s == -1 else 'false'})" for a, b, s in ch)
    L.append(f"def origChunk{k} : List (Nat × Nat × Bool) := [{body}]\n")
L.append("/-- OPH's edge list (`seam_complex(...)[\"edges\"]` with `edge_sign_of`), original ids. -/\n"
         "def origEdges : List (Nat × Nat × Bool) :=\n  "
         + " ++ ".join(f"origChunk{k}" for k in range(len(echunks))) + "\n")
s_new = emit(newT, "newT", "NTree"); s_old = emit(oldT, "oldT", "NTree")
s_perm = emit(permT, "permT", "NTree"); s_inv = emit(invPermT, "invPermT", "NTree")
# Trie Edge values need Edge syntax
def emit_e(t, name, depth=0):
    if t is None: return "leaf"
    v, l, r = t
    vs = "none" if v is None else f"(some {fmt_edge(v)})"
    s = f"(node {vs} {emit_e(l, name, depth+1)} {emit_e(r, name, depth+1)})"
    if depth == 4:
        defs.append(f"def {name}_{len(defs)} : Trie Edge := {s}\n")
        return f"{name}_{len(defs)-1}"
    return s
s_et = emit_e(edgesT, "edgesT")
L += defs
L.append(f"/-- hint: carrier id ↦ BFS label -/\ndef newT : NTree := {s_new}\n")
L.append(f"/-- hint: BFS label ↦ carrier id -/\ndef oldT : NTree := {s_old}\n")
L.append(f"/-- hint: original edge index ↦ index in `edges` (OphData.lean) -/\ndef permT : NTree := {s_perm}\n")
L.append(f"/-- hint: inverse of `permT` -/\ndef invPermT : NTree := {s_inv}\n")
L.append(f"/-- hint: table of `edges.map canon` by index -/\ndef edgesT : Trie Edge := {s_et}\n")
L.append("end GapScout.Oph\n")
out = "\n".join(L)
open("OphGap/OphOrigData.lean", "w").write(out)
print("OphOrigData.lean bytes", len(out), "sha256", hashlib.sha256(out.encode()).hexdigest())
print("nodes", n, "edges", len(edges), "max id", max(nodes), "tree defs", len(defs))
