"""Emit OphGap/Slices/*.lean: one kernel evaluation per module, chained by imports so Lake
builds them strictly one after another (each needs ~7 GB of imports plus its own kernel work;
several at once would cross the box's memory guard). Proved `_split` lemmas reassemble the
full checks in OphOrigWitness.lean."""
import os
os.makedirs("OphGap/Slices", exist_ok=True)
N, M = 8662, 11816
slices = []  # (module, statement-name, statement, needs maxRecDepth)
# nodes: 3000-windows
slices.append(("N1", "nodes_1", "nodesOk n newT oldT (origNodes.take 3000) = true"))
slices.append(("N2", "nodes_2", "nodesOk n newT oldT ((origNodes.drop 3000).take 3000) = true"))
slices.append(("N3", "nodes_3", "nodesOk n newT oldT ((origNodes.drop 3000).drop 3000) = true"))
slices.append(("E1", "endpoints_1", "endpointsOk n newT oldT (origEdges.take 4000) = true"))
slices.append(("E2", "endpoints_2", "endpointsOk n newT oldT ((origEdges.drop 4000).take 4000) = true"))
slices.append(("E3", "endpoints_3", "endpointsOk n newT oldT ((origEdges.drop 4000).drop 4000) = true"))
slices.append(("T1", "edgesT_1", "edgesTOk edgesT 0 (edges.take 4000) = true"))
slices.append(("T2", "edgesT_2", "edgesTOk edgesT 4000 ((edges.drop 4000).take 4000) = true"))
slices.append(("T3", "edgesT_3", "edgesTOk edgesT 8000 ((edges.drop 4000).drop 4000) = true"))
D2 = "((origEdges.drop 3000).drop 3000)"
slices.append(("P1", "perm_1", "permOk (newF newT) permT invPermT edgesT edges.length 0 (origEdges.take 3000) = true"))
slices.append(("P2", "perm_2", "permOk (newF newT) permT invPermT edgesT edges.length 3000 ((origEdges.drop 3000).take 3000) = true"))
slices.append(("P3", "perm_3", f"permOk (newF newT) permT invPermT edgesT edges.length 6000 ({D2}.take 3000) = true"))
slices.append(("P4", "perm_4", f"permOk (newF newT) permT invPermT edgesT edges.length 9000 ({D2}.drop 3000) = true"))
prev = None
for mod, name, stmt in slices:
    imp = f"import OphGap.Slices.{prev}" if prev else "import OphGap.OphWitness\nimport OphGap.OphOrigData"
    extra = ""
    if prev is None:
        extra = '''
theorem origNodes_length : origNodes.length = 8662 := by decide +kernel
theorem origEdges_length : origEdges.length = 11816 := by decide +kernel
theorem part_len : decide (origNodes.length = n) = true := by decide +kernel
theorem part_lenEq : decide (origEdges.length = edges.length) = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem part_sorted : sortedOk origNodes = true := by decide +kernel
'''
    body = f'''{imp}

/-! AUTO-GENERATED by tools/gen_slices.py: one kernel evaluation of a window of a certificate
check. Chained imports force Lake to build the slices one at a time. -/

namespace GapScout.Oph
{extra}
set_option maxRecDepth 100000 in
theorem {name} : {stmt} := by decide +kernel

end GapScout.Oph
'''
    open(f"OphGap/Slices/{mod}.lean", "w").write(body)
    prev = mod
print("last slice:", prev)
